main: main.o Cine.o Comentario.o ControladorCineFuncion.o ControladorPelicula.o ControladorReserva.o ControladorUsuario.o Credito.o Debito.o DtCine.o DtCredito.o DtDebito.o DtDireccion.o DtFecha.o DtFuncion.o DtHorario.o DtPelicula.o DtPuntaje.o DtReserva.o DtSala.o Fabrica.o Funcion.o Pelicula.o Puntaje.o Reloj.o Reserva.o Sala.o Usuario.o
	g++ -Wall -Werror Cine.o Comentario.o ControladorCineFuncion.o ControladorPelicula.o ControladorReserva.o ControladorUsuario.o Credito.o Debito.o DtCine.o DtCredito.o DtDebito.o DtDireccion.o DtFecha.o DtFuncion.o DtHorario.o DtPelicula.o DtPuntaje.o DtReserva.o DtSala.o Fabrica.o Funcion.o Pelicula.o Puntaje.o Reloj.o Reserva.o Sala.o Usuario.o main.o -o main

main.o: main.cpp
	g++ -c main.cpp

Comentario.o: Comentario.cpp
	g++ -c Comentario.cpp	
	
ControladorCineFuncion.o: ControladorCineFuncion.cpp
	g++ -c ControladorCineFuncion.cpp		
	
ControladorPelicula.o: ControladorPelicula.cpp
	g++ -c ControladorPelicula.cpp	

ControladorReserva.o: ControladorReserva.cpp
	g++ -c ControladorReserva.cpp	

ControladorUsuario.o: ControladorUsuario.cpp
	g++ -c ControladorUsuario.cpp	

Credito.o: Credito.cpp
	g++ -c Credito.cpp	

Debito.o: Debito.cpp
	g++ -c Debito.cpp	

DtCine.o: DtCine.cpp
	g++ -c DtCine.cpp	

DtCredito.o: DtCredito.cpp
	g++ -c DtCredito.cpp	

DtDebito.o: DtDebito.cpp
	g++ -c DtDebito.cpp	

DtDireccion.o: DtDireccion.cpp
	g++ -c DtDireccion.cpp	

DtFecha.o: DtFecha.cpp
	g++ -c DtFecha.cpp	

DtFuncion.o: DtFuncion.cpp
	g++ -c DtFuncion.cpp	

DtHorario.o: DtHorario.cpp
	g++ -c DtHorario.cpp	

DtPelicula.o: DtPelicula.cpp
	g++ -c DtPelicula.cpp

DtPuntaje.o: DtPuntaje.cpp
	g++ -c DtPuntaje.cpp

DtReserva.o: DtReserva.cpp
	g++ -c DtReserva.cpp

DtSala.o: DtSala.cpp
	g++ -c DtSala.cpp

Fabrica.o: Fabrica.cpp
	g++ -c Fabrica.cpp

Funcion.o: Funcion.cpp
	g++ -c Funcion.cpp

Pelicula.o: Pelicula.cpp
	g++ -c Pelicula.cpp

Puntaje.o: Puntaje.cpp
	g++ -c Puntaje.cpp

Reloj.o: Reloj.cpp
	g++ -c Reloj.cpp	
	
Reserva.o: Reserva.cpp
	g++ -c Reserva.cpp	

Sala.o: Sala.cpp
	g++ -c Sala.cpp	

Usuario.o: Usuario.cpp
	g++ -c Usuario.cpp	